---
title: "erinea_OriginalHomeworkCode_03"
author: "Erin Anderson"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
  

  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import csv, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
zombie_data <- read.csv("~/Desktop/zombies.csv", sep = ",", header = TRUE, stringsAsFactors = FALSE)
```

## Problem 1: Means
```{r read csv, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
zombie_data
height <- zombie_data[["height"]]
weight <- zombie_data[["weight"]]
killed <- zombie_data[["zombies_killed"]]
age <- zombie_data[["age"]]
years_of_education <- zombie_data[["years_of_education"]]
mean_height <- mean(height)
mean_height
mean_weight <- mean(weight)
mean_weight
mean_age <- mean(age)
mean_age
mean_killed <- mean(killed)
mean(killed)
mean_years_of_education <- mean(years_of_education)
mean_years_of_education
```

## Problem 1: Standard Deviations
```{r standard deviation, include=TRUE}
sum_squared_diff_age <- sum((age - mean_age)^2)
population_sd_age <- sqrt(sum_squared_diff_age / length(age))
population_sd_age
sum_squared_diff_weight <- sum((weight - mean_weight)^2)
population_sd_weight <- sqrt(sum_squared_diff_weight / length(weight))
population_sd_weight
sum_squared_diff_height <- sum((height - mean_height)^2)
population_sd_height <- sqrt(sum_squared_diff_height / length(height))
population_sd_height
sum_squared_diff_killed <- sum((killed - mean_killed)^2)
population_sd_killed <- sqrt(sum_squared_diff_killed / length(killed))
population_sd_killed
sum_squared_diff_years <- sum((years_of_education - mean_years_of_education)^2)
population_sd_years <- sqrt(sum_squared_diff_years / length(years_of_education))
population_sd_years
```

## Problem 2: Age
```{r boxplot of age, include=TRUE}
library(ggplot2)
box_plot <- ggplot(data = zombie_data, aes(x = gender, y = (age)))
box_plot <- box_plot + geom_boxplot()
box_plot <- box_plot + theme(axis.text.x = element_text(angle = 90))
box_plot <- box_plot + ylab("Age") + xlab("Gender")
box_plot
```

## Problem 2: Weight
```{r boxplot of weight, include=TRUE}
library(ggplot2)
box_plot_2 <- ggplot(data = zombie_data, aes(x = gender, y = (weight)))
box_plot_2 <- box_plot_2 + geom_boxplot()
box_plot_2 <- box_plot_2 + theme(axis.text.x = element_text(angle = 90))
box_plot_2 <- box_plot_2 + ylab("Weight") + xlab("Gender")
box_plot_2
```

## Problem 2: Height
```{r boxplot of height, include=TRUE}
library(ggplot2)
box_plot_3 <- ggplot(data = zombie_data, aes(x = gender, y = (height)))
box_plot_3 <- box_plot_3 + geom_boxplot()
box_plot_3 <- box_plot_3 + theme(axis.text.x = element_text(angle = 90))
box_plot_3 <- box_plot_3 + ylab("Height") + xlab("Gender")
box_plot_3
```

## Problem 2: Zombies Killed
```{r boxplot of kiled, include=TRUE}
library(ggplot2)
box_plot_4 <- ggplot(data = zombie_data, aes(x = gender, y = (killed)))
box_plot_4 <- box_plot_4 + geom_boxplot()
box_plot_4 <- box_plot_4 + theme(axis.text.x = element_text(angle = 90))
box_plot_4 <- box_plot_4 + ylab("Zombies Killed") + xlab("Gender")
box_plot_4
```

## Problem 2: Years of Education
```{r boxplot of years, include=TRUE}
library(ggplot2)
box_plot_5 <- ggplot(data = zombie_data, aes(x = gender, y = (years_of_education)))
box_plot_5 <- box_plot_5 + geom_boxplot()
box_plot_5 <- box_plot_5 + theme(axis.text.x = element_text(angle = 90))
box_plot_5 <- box_plot_5 + ylab("Years of Education") + xlab("Gender")
box_plot_5
```

## Problem 3: Height and Age
```{r scatterplot 1, include=TRUE}
scatterplot <- ggplot(data = zombie_data, aes(x = age, y = height))
scatterplot <- scatterplot + geom_point()
scatterplot <- scatterplot + geom_smooth(method = "lm")
scatterplot
```

## Problem 3: Weight and Age
```{r scatterplot 2, include=TRUE}
scatterplot_2 <- ggplot(data = zombie_data, aes(x = age, y = weight))
scatterplot_2 <- scatterplot_2 + geom_point()
scatterplot_2 <- scatterplot_2 + geom_smooth(method = "lm")
scatterplot_2
```

## Problem 3: Weight and Height
```{r scatterplot 3, include=TRUE}
scatterplot_3 <- ggplot(data = zombie_data, aes(x = age, y = weight))
scatterplot_3 <- scatterplot_3 + geom_point()
scatterplot_3 <- scatterplot_3 + geom_smooth(method = "lm")
scatterplot_3
```

## Problem 4: Age
```{r histogram 1, include=TRUE}
hist_age <- hist(age, probability = TRUE, main = "Age",
    xlab = "Age", ylab = "probability", xlim = c(10,30))
hist_age
```

```{r histogram 2, include=TRUE}
hist_weight <- hist(weight, probability = TRUE, main = "Weight",
    xlab = "Weight", ylab = "probability", xlim = c(100,250))
hist_weight
```
```{r histogram 3, include=TRUE}
hist_killed <- hist(killed, probability = TRUE, main = "Killed",
    xlab = "Killed", ylab = "probability", xlim = c(0,12))
hist_killed
```

